-- Migration 005: Teacher Foundation (Sprint 4)
-- See docs/database/MIGRATION_PLAN.md's Sprint 4 status note and
-- docs/DECISIONS.md's Sprint 4 entry.
--
-- Contains one hand-added constraint not expressible in schema.prisma
-- syntax: a partial unique index enforcing "exactly one Class Teacher per
-- section per year", scoped WHERE is_class_teacher = true, per
-- docs/database/DATABASE_REVIEW.md § 7 — the Prisma-native
-- @@unique([academic_year_id, section_id, subject_id]) below does NOT
-- cover this rule, since Postgres treats multiple NULL subject_id values
-- as distinct, not colliding.

-- CreateEnum
CREATE TYPE "teacher_status" AS ENUM ('ACTIVE', 'ON_LEAVE', 'EXITED');

-- CreateTable
CREATE TABLE "teachers" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "gender" TEXT,
    "date_of_birth" TIMESTAMPTZ(3),
    "photo_url" TEXT,
    "status" "teacher_status" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "teachers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_qualifications" (
    "id" TEXT NOT NULL,
    "teacher_id" TEXT NOT NULL,
    "qualification_type" TEXT NOT NULL,
    "institution" TEXT,
    "year_completed" INTEGER,
    "certificate_document_id" TEXT,
    "deleted_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "teacher_qualifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_assignments" (
    "id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "teacher_id" TEXT NOT NULL,
    "section_id" TEXT NOT NULL,
    "subject_id" TEXT,
    "is_class_teacher" BOOLEAN NOT NULL DEFAULT false,
    "deleted_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "teacher_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "teachers_user_id_key" ON "teachers"("user_id");

-- CreateIndex
CREATE INDEX "teacher_qualifications_teacher_id_idx" ON "teacher_qualifications"("teacher_id");

-- CreateIndex
CREATE INDEX "teacher_assignments_teacher_id_academic_year_id_idx" ON "teacher_assignments"("teacher_id", "academic_year_id");

-- CreateIndex
CREATE INDEX "teacher_assignments_section_id_academic_year_id_idx" ON "teacher_assignments"("section_id", "academic_year_id");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_assignments_academic_year_id_section_id_subject_id_key" ON "teacher_assignments"("academic_year_id", "section_id", "subject_id");

-- CreateIndex (hand-added, not generated by Prisma)
-- Partial unique index: exactly one Class Teacher per section per year.
-- See docs/database/DATABASE_REVIEW.md § 7.
CREATE UNIQUE INDEX "teacher_assignments_one_class_teacher_per_section"
    ON "teacher_assignments" ("section_id", "academic_year_id")
    WHERE "is_class_teacher" = true;

-- AddForeignKey
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("school_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_qualifications" ADD CONSTRAINT "teacher_qualifications_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE SET NULL ON UPDATE CASCADE;
