-- Migration 001: School Foundation
-- See docs/database/MIGRATION_PLAN.md § 2.
--
-- Contains one hand-added constraint not expressible in schema.prisma syntax:
-- a partial unique index enforcing "exactly one current academic year per
-- school" (docs/database/CONSTRAINT_STRATEGY.md § 3,
-- docs/database/PRISMA_IMPLEMENTATION_GUIDE.md § 3). Prisma will preserve
-- this hand-edit as long as this file isn't regenerated.

-- CreateEnum
CREATE TYPE "school_status" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "academic_year_status" AS ENUM ('ACTIVE', 'CLOSED');

-- CreateTable
CREATE TABLE "schools" (
    "school_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "short_name" TEXT,
    "affiliation_board" TEXT,
    "udise_code" TEXT,
    "status" "school_status" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "schools_pkey" PRIMARY KEY ("school_id")
);

-- CreateTable
CREATE TABLE "academic_years" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "start_date" TIMESTAMPTZ(3) NOT NULL,
    "end_date" TIMESTAMPTZ(3) NOT NULL,
    "is_current" BOOLEAN NOT NULL DEFAULT false,
    "status" "academic_year_status" NOT NULL DEFAULT 'ACTIVE',
    "promotion_policy" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "academic_years_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "schools_udise_code_key" ON "schools"("udise_code");

-- CreateIndex
CREATE INDEX "academic_years_school_id_is_current_idx" ON "academic_years"("school_id", "is_current");

-- CreateIndex
CREATE UNIQUE INDEX "academic_years_school_id_label_key" ON "academic_years"("school_id", "label");

-- CreateIndex (hand-added, not generated by Prisma)
-- Partial unique index: enforces at most one AcademicYear with is_current = true
-- per school. See docs/database/CONSTRAINT_STRATEGY.md § 3.
CREATE UNIQUE INDEX "academic_years_one_current_per_school"
    ON "academic_years" ("school_id")
    WHERE "is_current" = true;

-- AddForeignKey
ALTER TABLE "academic_years" ADD CONSTRAINT "academic_years_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("school_id") ON DELETE RESTRICT ON UPDATE CASCADE;
