-- Migration 003: Academic Foundation (Sprint 2)
-- See docs/database/MIGRATION_PLAN.md's Sprint 2 status note and
-- docs/DECISIONS.md's Sprint 2 entry.
--
-- Contains three hand-added constraints not expressible in schema.prisma
-- syntax: partial unique indexes enforcing "unique name among non-deleted
-- rows" for school_classes, sections, and subjects, per
-- docs/database/SOFT_DELETE_STRATEGY.md § 2 and
-- docs/database/INDEXING_STRATEGY.md § 1. Prisma will preserve this
-- hand-edit as long as this file isn't regenerated.

-- CreateTable
CREATE TABLE "school_classes" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "school_classes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sections" (
    "id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "school_class_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "capacity" INTEGER,
    "deleted_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "sections_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subjects" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT,
    "deleted_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "subjects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "school_classes_school_id_name_idx" ON "school_classes"("school_id", "name");

-- CreateIndex
CREATE INDEX "sections_school_class_id_academic_year_id_name_idx" ON "sections"("school_class_id", "academic_year_id", "name");

-- CreateIndex
CREATE INDEX "subjects_school_id_name_idx" ON "subjects"("school_id", "name");

-- CreateIndex (hand-added, not generated by Prisma)
-- Partial unique index: a class name must be unique per school among
-- non-deleted rows. See docs/database/SOFT_DELETE_STRATEGY.md § 2.
CREATE UNIQUE INDEX "school_classes_one_name_per_school"
    ON "school_classes" ("school_id", "name")
    WHERE "deleted_at" IS NULL;

-- CreateIndex (hand-added, not generated by Prisma)
-- Partial unique index: a section name must be unique per class per
-- academic year among non-deleted rows.
CREATE UNIQUE INDEX "sections_one_name_per_class_per_year"
    ON "sections" ("school_class_id", "academic_year_id", "name")
    WHERE "deleted_at" IS NULL;

-- CreateIndex (hand-added, not generated by Prisma)
-- Partial unique index: a subject name must be unique per school among
-- non-deleted rows.
CREATE UNIQUE INDEX "subjects_one_name_per_school"
    ON "subjects" ("school_id", "name")
    WHERE "deleted_at" IS NULL;

-- AddForeignKey
ALTER TABLE "school_classes" ADD CONSTRAINT "school_classes_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("school_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sections" ADD CONSTRAINT "sections_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sections" ADD CONSTRAINT "sections_school_class_id_fkey" FOREIGN KEY ("school_class_id") REFERENCES "school_classes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subjects" ADD CONSTRAINT "subjects_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("school_id") ON DELETE RESTRICT ON UPDATE CASCADE;
